/*!
 * https://github.com/SamsungDForum/JuvoPlayer
 * Copyright 2018, Samsung Electronics Co., Ltd
 * Licensed under the MIT license
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

﻿//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace JuvoPlayer.Tests.UnitTests {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mpeg:dash:schema:mpd:2011")]
    [System.Xml.Serialization.XmlRootAttribute("MPD", Namespace="urn:mpeg:dash:schema:mpd:2011", IsNullable=false)]
    public partial class MPDtype {
        
        private ProgramInformationType[] programInformationField;
        
        private BaseURLType[] baseURLField;
        
        private string[] locationField;
        
        private PeriodType[] periodField;
        
        private MetricsType[] metricsField;
        
        private DescriptorType[] essentialPropertyField;
        
        private DescriptorType[] supplementalPropertyField;
        
        private DescriptorType[] uTCTimingField;
        
        private System.Xml.XmlElement[] anyField;
        
        private string idField;
        
        private string profilesField;
        
        private PresentationType typeField;
        
        private System.DateTime availabilityStartTimeField;
        
        private bool availabilityStartTimeFieldSpecified;
        
        private System.DateTime availabilityEndTimeField;
        
        private bool availabilityEndTimeFieldSpecified;
        
        private System.DateTime publishTimeField;
        
        private bool publishTimeFieldSpecified;
        
        private string mediaPresentationDurationField;
        
        private string minimumUpdatePeriodField;
        
        private string minBufferTimeField;
        
        private string timeShiftBufferDepthField;
        
        private string suggestedPresentationDelayField;
        
        private string maxSegmentDurationField;
        
        private string maxSubsegmentDurationField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        public MPDtype() {
            this.typeField = PresentationType.@static;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ProgramInformation")]
        public ProgramInformationType[] ProgramInformation {
            get {
                return this.programInformationField;
            }
            set {
                this.programInformationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BaseURL")]
        public BaseURLType[] BaseURL {
            get {
                return this.baseURLField;
            }
            set {
                this.baseURLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Location", DataType="anyURI")]
        public string[] Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Period")]
        public PeriodType[] Period {
            get {
                return this.periodField;
            }
            set {
                this.periodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Metrics")]
        public MetricsType[] Metrics {
            get {
                return this.metricsField;
            }
            set {
                this.metricsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EssentialProperty")]
        public DescriptorType[] EssentialProperty {
            get {
                return this.essentialPropertyField;
            }
            set {
                this.essentialPropertyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SupplementalProperty")]
        public DescriptorType[] SupplementalProperty {
            get {
                return this.supplementalPropertyField;
            }
            set {
                this.supplementalPropertyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("UTCTiming")]
        public DescriptorType[] UTCTiming {
            get {
                return this.uTCTimingField;
            }
            set {
                this.uTCTimingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string profiles {
            get {
                return this.profilesField;
            }
            set {
                this.profilesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(PresentationType.@static)]
        public PresentationType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime availabilityStartTime {
            get {
                return this.availabilityStartTimeField;
            }
            set {
                this.availabilityStartTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool availabilityStartTimeSpecified {
            get {
                return this.availabilityStartTimeFieldSpecified;
            }
            set {
                this.availabilityStartTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime availabilityEndTime {
            get {
                return this.availabilityEndTimeField;
            }
            set {
                this.availabilityEndTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool availabilityEndTimeSpecified {
            get {
                return this.availabilityEndTimeFieldSpecified;
            }
            set {
                this.availabilityEndTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime publishTime {
            get {
                return this.publishTimeField;
            }
            set {
                this.publishTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool publishTimeSpecified {
            get {
                return this.publishTimeFieldSpecified;
            }
            set {
                this.publishTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="duration")]
        public string mediaPresentationDuration {
            get {
                return this.mediaPresentationDurationField;
            }
            set {
                this.mediaPresentationDurationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="duration")]
        public string minimumUpdatePeriod {
            get {
                return this.minimumUpdatePeriodField;
            }
            set {
                this.minimumUpdatePeriodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="duration")]
        public string minBufferTime {
            get {
                return this.minBufferTimeField;
            }
            set {
                this.minBufferTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="duration")]
        public string timeShiftBufferDepth {
            get {
                return this.timeShiftBufferDepthField;
            }
            set {
                this.timeShiftBufferDepthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="duration")]
        public string suggestedPresentationDelay {
            get {
                return this.suggestedPresentationDelayField;
            }
            set {
                this.suggestedPresentationDelayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="duration")]
        public string maxSegmentDuration {
            get {
                return this.maxSegmentDurationField;
            }
            set {
                this.maxSegmentDurationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="duration")]
        public string maxSubsegmentDuration {
            get {
                return this.maxSubsegmentDurationField;
            }
            set {
                this.maxSubsegmentDurationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mpeg:dash:schema:mpd:2011")]
    public partial class ProgramInformationType {
        
        private string titleField;
        
        private string sourceField;
        
        private string copyrightField;
        
        private System.Xml.XmlElement[] anyField;
        
        private string langField;
        
        private string moreInformationURLField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public string Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        public string Copyright {
            get {
                return this.copyrightField;
            }
            set {
                this.copyrightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="language")]
        public string lang {
            get {
                return this.langField;
            }
            set {
                this.langField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string moreInformationURL {
            get {
                return this.moreInformationURLField;
            }
            set {
                this.moreInformationURLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mpeg:dash:schema:mpd:2011")]
    public partial class RangeType {
        
        private string starttimeField;
        
        private string durationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="duration")]
        public string starttime {
            get {
                return this.starttimeField;
            }
            set {
                this.starttimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="duration")]
        public string duration {
            get {
                return this.durationField;
            }
            set {
                this.durationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mpeg:dash:schema:mpd:2011")]
    public partial class MetricsType {
        
        private DescriptorType[] reportingField;
        
        private RangeType[] rangeField;
        
        private System.Xml.XmlElement[] anyField;
        
        private string metricsField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Reporting")]
        public DescriptorType[] Reporting {
            get {
                return this.reportingField;
            }
            set {
                this.reportingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Range")]
        public RangeType[] Range {
            get {
                return this.rangeField;
            }
            set {
                this.rangeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string metrics {
            get {
                return this.metricsField;
            }
            set {
                this.metricsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mpeg:dash:schema:mpd:2011")]
    public partial class DescriptorType {
        
        private System.Xml.XmlElement[] anyField;
        
        private string schemeIdUriField;
        
        private string valueField;
        
        private string idField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string schemeIdUri {
            get {
                return this.schemeIdUriField;
            }
            set {
                this.schemeIdUriField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mpeg:dash:schema:mpd:2011")]
    public partial class SubsetType {
        
        private uint[] containsField;
        
        private string idField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint[] contains {
            get {
                return this.containsField;
            }
            set {
                this.containsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mpeg:dash:schema:mpd:2011")]
    public partial class ContentComponentType {
        
        private DescriptorType[] accessibilityField;
        
        private DescriptorType[] roleField;
        
        private DescriptorType[] ratingField;
        
        private DescriptorType[] viewpointField;
        
        private System.Xml.XmlElement[] anyField;
        
        private uint idField;
        
        private bool idFieldSpecified;
        
        private string langField;
        
        private string contentTypeField;
        
        private string parField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Accessibility")]
        public DescriptorType[] Accessibility {
            get {
                return this.accessibilityField;
            }
            set {
                this.accessibilityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Role")]
        public DescriptorType[] Role {
            get {
                return this.roleField;
            }
            set {
                this.roleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Rating")]
        public DescriptorType[] Rating {
            get {
                return this.ratingField;
            }
            set {
                this.ratingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Viewpoint")]
        public DescriptorType[] Viewpoint {
            get {
                return this.viewpointField;
            }
            set {
                this.viewpointField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="language")]
        public string lang {
            get {
                return this.langField;
            }
            set {
                this.langField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string contentType {
            get {
                return this.contentTypeField;
            }
            set {
                this.contentTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string par {
            get {
                return this.parField;
            }
            set {
                this.parField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }

    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:mpeg:dash:schema:mpd:2011")]
    public partial class ContentProtectionType
    {
        private string CencDefaultKIDField;
        private string SchemeIdUriField;
        private string ValueField;
        private System.Xml.XmlNode[] DataField;
        
        [System.Xml.Serialization.XmlElementAttribute("default_KID")]
        public string CencDefaultKID
        {
            get
            {
                return this.CencDefaultKIDField;
            }
            set
            {
                this.CencDefaultKIDField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("schemeIdUri")]
        public string SchemeIdUri
        {
            get
            {
                return this.SchemeIdUriField;
            }
            set
            {
                this.SchemeIdUriField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("value")]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
        [System.Xml.Serialization.XmlAnyElement()]
        public System.Xml.XmlNode[] Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SubRepresentationType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RepresentationType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AdaptationSetType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mpeg:dash:schema:mpd:2011")]
    public partial class RepresentationBaseType {
        
        private DescriptorType[] framePackingField;
        
        private DescriptorType[] audioChannelConfigurationField;

        private DescriptorType[] contentProtectionField;

        private DescriptorType[] essentialPropertyField;
        
        private DescriptorType[] supplementalPropertyField;
        
        private EventStreamType[] inbandEventStreamField;
        
        private System.Xml.XmlElement[] anyField;
        
        private string profilesField;
        
        private uint widthField;
        
        private bool widthFieldSpecified;
        
        private uint heightField;
        
        private bool heightFieldSpecified;
        
        private string sarField;
        
        private string frameRateField;
        
        private string audioSamplingRateField;
        
        private string mimeTypeField;
        
        private string segmentProfilesField;
        
        private string codecsField;
        
        private double maximumSAPPeriodField;
        
        private bool maximumSAPPeriodFieldSpecified;
        
        private uint startWithSAPField;
        
        private bool startWithSAPFieldSpecified;
        
        private double maxPlayoutRateField;
        
        private bool maxPlayoutRateFieldSpecified;
        
        private bool codingDependencyField;
        
        private bool codingDependencyFieldSpecified;
        
        private VideoScanType scanTypeField;
        
        private bool scanTypeFieldSpecified;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FramePacking")]
        public DescriptorType[] FramePacking {
            get {
                return this.framePackingField;
            }
            set {
                this.framePackingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AudioChannelConfiguration")]
        public DescriptorType[] AudioChannelConfiguration {
            get {
                return this.audioChannelConfigurationField;
            }
            set {
                this.audioChannelConfigurationField = value;
            }
        }

        /// <remarks/>
   
        [System.Xml.Serialization.XmlElementAttribute("ContentProtection")]
        public DescriptorType[] ContentProtection {
            get {
                return this.contentProtectionField;
            }
            set {
                this.contentProtectionField = value;
            }
        }
        
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EssentialProperty")]
        public DescriptorType[] EssentialProperty {
            get {
                return this.essentialPropertyField;
            }
            set {
                this.essentialPropertyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SupplementalProperty")]
        public DescriptorType[] SupplementalProperty {
            get {
                return this.supplementalPropertyField;
            }
            set {
                this.supplementalPropertyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("InbandEventStream")]
        public EventStreamType[] InbandEventStream {
            get {
                return this.inbandEventStreamField;
            }
            set {
                this.inbandEventStreamField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string profiles {
            get {
                return this.profilesField;
            }
            set {
                this.profilesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool widthSpecified {
            get {
                return this.widthFieldSpecified;
            }
            set {
                this.widthFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool heightSpecified {
            get {
                return this.heightFieldSpecified;
            }
            set {
                this.heightFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string sar {
            get {
                return this.sarField;
            }
            set {
                this.sarField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string frameRate {
            get {
                return this.frameRateField;
            }
            set {
                this.frameRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string audioSamplingRate {
            get {
                return this.audioSamplingRateField;
            }
            set {
                this.audioSamplingRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string mimeType {
            get {
                return this.mimeTypeField;
            }
            set {
                this.mimeTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string segmentProfiles {
            get {
                return this.segmentProfilesField;
            }
            set {
                this.segmentProfilesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string codecs {
            get {
                return this.codecsField;
            }
            set {
                this.codecsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double maximumSAPPeriod {
            get {
                return this.maximumSAPPeriodField;
            }
            set {
                this.maximumSAPPeriodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maximumSAPPeriodSpecified {
            get {
                return this.maximumSAPPeriodFieldSpecified;
            }
            set {
                this.maximumSAPPeriodFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint startWithSAP {
            get {
                return this.startWithSAPField;
            }
            set {
                this.startWithSAPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool startWithSAPSpecified {
            get {
                return this.startWithSAPFieldSpecified;
            }
            set {
                this.startWithSAPFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double maxPlayoutRate {
            get {
                return this.maxPlayoutRateField;
            }
            set {
                this.maxPlayoutRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxPlayoutRateSpecified {
            get {
                return this.maxPlayoutRateFieldSpecified;
            }
            set {
                this.maxPlayoutRateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool codingDependency {
            get {
                return this.codingDependencyField;
            }
            set {
                this.codingDependencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codingDependencySpecified {
            get {
                return this.codingDependencyFieldSpecified;
            }
            set {
                this.codingDependencyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public VideoScanType scanType {
            get {
                return this.scanTypeField;
            }
            set {
                this.scanTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool scanTypeSpecified {
            get {
                return this.scanTypeFieldSpecified;
            }
            set {
                this.scanTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mpeg:dash:schema:mpd:2011")]
    public partial class EventStreamType {
        
        private EventType[] eventField;
        
        private System.Xml.XmlElement[] anyField;
        
        private string hrefField;
        
        private actuateType actuateField;
        
        private string schemeIdUriField;
        
        private string valueField;
        
        private uint timescaleField;
        
        private bool timescaleFieldSpecified;
        
        public EventStreamType() {
            this.actuateField = actuateType.onRequest;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Event")]
        public EventType[] Event {
            get {
                return this.eventField;
            }
            set {
                this.eventField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/1999/xlink", DataType="anyURI")]
        public string href {
            get {
                return this.hrefField;
            }
            set {
                this.hrefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/1999/xlink")]
        [System.ComponentModel.DefaultValueAttribute(actuateType.onRequest)]
        public actuateType actuate {
            get {
                return this.actuateField;
            }
            set {
                this.actuateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string schemeIdUri {
            get {
                return this.schemeIdUriField;
            }
            set {
                this.schemeIdUriField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint timescale {
            get {
                return this.timescaleField;
            }
            set {
                this.timescaleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool timescaleSpecified {
            get {
                return this.timescaleFieldSpecified;
            }
            set {
                this.timescaleFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mpeg:dash:schema:mpd:2011")]
    public partial class EventType {
        
        private System.Xml.XmlElement[] anyField;
        
        private ulong presentationTimeField;
        
        private ulong durationField;
        
        private bool durationFieldSpecified;
        
        private uint idField;
        
        private bool idFieldSpecified;
        
        private string messageDataField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        public EventType() {
            this.presentationTimeField = ((ulong)(0m));
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(ulong), "0")]
        public ulong presentationTime {
            get {
                return this.presentationTimeField;
            }
            set {
                this.presentationTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ulong duration {
            get {
                return this.durationField;
            }
            set {
                this.durationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool durationSpecified {
            get {
                return this.durationFieldSpecified;
            }
            set {
                this.durationFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string messageData {
            get {
                return this.messageDataField;
            }
            set {
                this.messageDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/1999/xlink")]
    public enum actuateType {
        
        /// <remarks/>
        onLoad,
        
        /// <remarks/>
        onRequest,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mpeg:dash:schema:mpd:2011")]
    public enum VideoScanType {
        
        /// <remarks/>
        progressive,
        
        /// <remarks/>
        interlaced,
        
        /// <remarks/>
        unknown,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mpeg:dash:schema:mpd:2011")]
    public partial class SubRepresentationType : RepresentationBaseType {
        
        private uint levelField;
        
        private bool levelFieldSpecified;
        
        private uint[] dependencyLevelField;
        
        private uint bandwidthField;
        
        private bool bandwidthFieldSpecified;
        
        private string[] contentComponentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint level {
            get {
                return this.levelField;
            }
            set {
                this.levelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool levelSpecified {
            get {
                return this.levelFieldSpecified;
            }
            set {
                this.levelFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint[] dependencyLevel {
            get {
                return this.dependencyLevelField;
            }
            set {
                this.dependencyLevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint bandwidth {
            get {
                return this.bandwidthField;
            }
            set {
                this.bandwidthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool bandwidthSpecified {
            get {
                return this.bandwidthFieldSpecified;
            }
            set {
                this.bandwidthFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string[] contentComponent {
            get {
                return this.contentComponentField;
            }
            set {
                this.contentComponentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mpeg:dash:schema:mpd:2011")]
    public partial class RepresentationType : RepresentationBaseType {
        
        private BaseURLType[] baseURLField;
        
        private SubRepresentationType[] subRepresentationField;
        
        private SegmentBaseType segmentBaseField;
        
        private SegmentListType segmentListField;
        
        private SegmentTemplateType segmentTemplateField;
        
        private string idField;
        
        private uint bandwidthField;
        
        private uint qualityRankingField;
        
        private bool qualityRankingFieldSpecified;
        
        private string[] dependencyIdField;
        
        private string[] mediaStreamStructureIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BaseURL")]
        public BaseURLType[] BaseURL {
            get {
                return this.baseURLField;
            }
            set {
                this.baseURLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SubRepresentation")]
        public SubRepresentationType[] SubRepresentation {
            get {
                return this.subRepresentationField;
            }
            set {
                this.subRepresentationField = value;
            }
        }
        
        /// <remarks/>
        public SegmentBaseType SegmentBase {
            get {
                return this.segmentBaseField;
            }
            set {
                this.segmentBaseField = value;
            }
        }
        
        /// <remarks/>
        public SegmentListType SegmentList {
            get {
                return this.segmentListField;
            }
            set {
                this.segmentListField = value;
            }
        }
        
        /// <remarks/>
        public SegmentTemplateType SegmentTemplate {
            get {
                return this.segmentTemplateField;
            }
            set {
                this.segmentTemplateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint bandwidth {
            get {
                return this.bandwidthField;
            }
            set {
                this.bandwidthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint qualityRanking {
            get {
                return this.qualityRankingField;
            }
            set {
                this.qualityRankingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool qualityRankingSpecified {
            get {
                return this.qualityRankingFieldSpecified;
            }
            set {
                this.qualityRankingFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string[] dependencyId {
            get {
                return this.dependencyIdField;
            }
            set {
                this.dependencyIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string[] mediaStreamStructureId {
            get {
                return this.mediaStreamStructureIdField;
            }
            set {
                this.mediaStreamStructureIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mpeg:dash:schema:mpd:2011")]
    public partial class BaseURLType {
        
        private string serviceLocationField;
        
        private string byteRangeField;
        
        private double availabilityTimeOffsetField;
        
        private bool availabilityTimeOffsetFieldSpecified;
        
        private bool availabilityTimeCompleteField;
        
        private bool availabilityTimeCompleteFieldSpecified;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string serviceLocation {
            get {
                return this.serviceLocationField;
            }
            set {
                this.serviceLocationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string byteRange {
            get {
                return this.byteRangeField;
            }
            set {
                this.byteRangeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double availabilityTimeOffset {
            get {
                return this.availabilityTimeOffsetField;
            }
            set {
                this.availabilityTimeOffsetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool availabilityTimeOffsetSpecified {
            get {
                return this.availabilityTimeOffsetFieldSpecified;
            }
            set {
                this.availabilityTimeOffsetFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool availabilityTimeComplete {
            get {
                return this.availabilityTimeCompleteField;
            }
            set {
                this.availabilityTimeCompleteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool availabilityTimeCompleteSpecified {
            get {
                return this.availabilityTimeCompleteFieldSpecified;
            }
            set {
                this.availabilityTimeCompleteFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="anyURI")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MultipleSegmentBaseType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SegmentTemplateType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SegmentListType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mpeg:dash:schema:mpd:2011")]
    public partial class SegmentBaseType {
        
        private URLType initializationField;
        
        private URLType representationIndexField;
        
        private System.Xml.XmlElement[] anyField;
        
        private uint timescaleField;
        
        private bool timescaleFieldSpecified;
        
        private ulong presentationTimeOffsetField;
        
        private bool presentationTimeOffsetFieldSpecified;
        
        private string indexRangeField;
        
        private bool indexRangeExactField;
        
        private double availabilityTimeOffsetField;
        
        private bool availabilityTimeOffsetFieldSpecified;
        
        private bool availabilityTimeCompleteField;
        
        private bool availabilityTimeCompleteFieldSpecified;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        public SegmentBaseType() {
            this.indexRangeExactField = false;
        }
        
        /// <remarks/>
        public URLType Initialization {
            get {
                return this.initializationField;
            }
            set {
                this.initializationField = value;
            }
        }
        
        /// <remarks/>
        public URLType RepresentationIndex {
            get {
                return this.representationIndexField;
            }
            set {
                this.representationIndexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint timescale {
            get {
                return this.timescaleField;
            }
            set {
                this.timescaleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool timescaleSpecified {
            get {
                return this.timescaleFieldSpecified;
            }
            set {
                this.timescaleFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ulong presentationTimeOffset {
            get {
                return this.presentationTimeOffsetField;
            }
            set {
                this.presentationTimeOffsetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool presentationTimeOffsetSpecified {
            get {
                return this.presentationTimeOffsetFieldSpecified;
            }
            set {
                this.presentationTimeOffsetFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string indexRange {
            get {
                return this.indexRangeField;
            }
            set {
                this.indexRangeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool indexRangeExact {
            get {
                return this.indexRangeExactField;
            }
            set {
                this.indexRangeExactField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double availabilityTimeOffset {
            get {
                return this.availabilityTimeOffsetField;
            }
            set {
                this.availabilityTimeOffsetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool availabilityTimeOffsetSpecified {
            get {
                return this.availabilityTimeOffsetFieldSpecified;
            }
            set {
                this.availabilityTimeOffsetFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool availabilityTimeComplete {
            get {
                return this.availabilityTimeCompleteField;
            }
            set {
                this.availabilityTimeCompleteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool availabilityTimeCompleteSpecified {
            get {
                return this.availabilityTimeCompleteFieldSpecified;
            }
            set {
                this.availabilityTimeCompleteFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mpeg:dash:schema:mpd:2011")]
    public partial class URLType {
        
        private System.Xml.XmlElement[] anyField;
        
        private string sourceURLField;
        
        private string rangeField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string sourceURL {
            get {
                return this.sourceURLField;
            }
            set {
                this.sourceURLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string range {
            get {
                return this.rangeField;
            }
            set {
                this.rangeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SegmentTemplateType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SegmentListType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mpeg:dash:schema:mpd:2011")]
    public partial class MultipleSegmentBaseType : SegmentBaseType {
        
        private SegmentTimelineType segmentTimelineField;
        
        private URLType bitstreamSwitchingField;
        
        private uint durationField;
        
        private bool durationFieldSpecified;
        
        private uint startNumberField;
        
        private bool startNumberFieldSpecified;
        
        /// <remarks/>
        public SegmentTimelineType SegmentTimeline {
            get {
                return this.segmentTimelineField;
            }
            set {
                this.segmentTimelineField = value;
            }
        }
        
        /// <remarks/>
        public URLType BitstreamSwitching {
            get {
                return this.bitstreamSwitchingField;
            }
            set {
                this.bitstreamSwitchingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint duration {
            get {
                return this.durationField;
            }
            set {
                this.durationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool durationSpecified {
            get {
                return this.durationFieldSpecified;
            }
            set {
                this.durationFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint startNumber {
            get {
                return this.startNumberField;
            }
            set {
                this.startNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool startNumberSpecified {
            get {
                return this.startNumberFieldSpecified;
            }
            set {
                this.startNumberFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mpeg:dash:schema:mpd:2011")]
    public partial class SegmentTimelineType {
        
        private SegmentTimelineTypeS[] sField;
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("S")]
        public SegmentTimelineTypeS[] S {
            get {
                return this.sField;
            }
            set {
                this.sField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:mpeg:dash:schema:mpd:2011")]
    public partial class SegmentTimelineTypeS {
        
        private ulong tField;
        
        private bool tFieldSpecified;
        
        private ulong nField;
        
        private bool nFieldSpecified;
        
        private ulong dField;
        
        private string rField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        public SegmentTimelineTypeS() {
            this.rField = "0";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ulong t {
            get {
                return this.tField;
            }
            set {
                this.tField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tSpecified {
            get {
                return this.tFieldSpecified;
            }
            set {
                this.tFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ulong n {
            get {
                return this.nField;
            }
            set {
                this.nField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nSpecified {
            get {
                return this.nFieldSpecified;
            }
            set {
                this.nFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ulong d {
            get {
                return this.dField;
            }
            set {
                this.dField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        [System.ComponentModel.DefaultValueAttribute("0")]
        public string r {
            get {
                return this.rField;
            }
            set {
                this.rField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mpeg:dash:schema:mpd:2011")]
    public partial class SegmentTemplateType : MultipleSegmentBaseType {
        
        private string mediaField;
        
        private string indexField;
        
        private string initializationField;
        
        private string bitstreamSwitchingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string media {
            get {
                return this.mediaField;
            }
            set {
                this.mediaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string index {
            get {
                return this.indexField;
            }
            set {
                this.indexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string initialization {
            get {
                return this.initializationField;
            }
            set {
                this.initializationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string bitstreamSwitching {
            get {
                return this.bitstreamSwitchingField;
            }
            set {
                this.bitstreamSwitchingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mpeg:dash:schema:mpd:2011")]
    public partial class SegmentListType : MultipleSegmentBaseType {
        
        private SegmentURLType[] segmentURLField;
        
        private string hrefField;
        
        private actuateType actuateField;
        
        public SegmentListType() {
            this.actuateField = actuateType.onRequest;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SegmentURL")]
        public SegmentURLType[] SegmentURL {
            get {
                return this.segmentURLField;
            }
            set {
                this.segmentURLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/1999/xlink", DataType="anyURI")]
        public string href {
            get {
                return this.hrefField;
            }
            set {
                this.hrefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/1999/xlink")]
        [System.ComponentModel.DefaultValueAttribute(actuateType.onRequest)]
        public actuateType actuate {
            get {
                return this.actuateField;
            }
            set {
                this.actuateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mpeg:dash:schema:mpd:2011")]
    public partial class SegmentURLType {
        
        private System.Xml.XmlElement[] anyField;
        
        private string mediaField;
        
        private string mediaRangeField;
        
        private string indexField;
        
        private string indexRangeField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string media {
            get {
                return this.mediaField;
            }
            set {
                this.mediaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string mediaRange {
            get {
                return this.mediaRangeField;
            }
            set {
                this.mediaRangeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string index {
            get {
                return this.indexField;
            }
            set {
                this.indexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string indexRange {
            get {
                return this.indexRangeField;
            }
            set {
                this.indexRangeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mpeg:dash:schema:mpd:2011")]
    public partial class AdaptationSetType : RepresentationBaseType {
        
        private DescriptorType[] accessibilityField;
        
        private DescriptorType[] roleField;
        
        private DescriptorType[] ratingField;
        
        private DescriptorType[] viewpointField;
        
        private ContentComponentType[] contentComponentField;
        
        private BaseURLType[] baseURLField;
        
        private SegmentBaseType segmentBaseField;
        
        private SegmentListType segmentListField;
        
        private SegmentTemplateType segmentTemplateField;
        
        private RepresentationType[] representationField;
        
        private string hrefField;
        
        private actuateType actuateField;
        
        private uint idField;
        
        private bool idFieldSpecified;
        
        private uint groupField;
        
        private bool groupFieldSpecified;
        
        private string langField;
        
        private string contentTypeField;
        
        private string parField;
        
        private uint minBandwidthField;
        
        private bool minBandwidthFieldSpecified;
        
        private uint maxBandwidthField;
        
        private bool maxBandwidthFieldSpecified;
        
        private uint minWidthField;
        
        private bool minWidthFieldSpecified;
        
        private uint maxWidthField;
        
        private bool maxWidthFieldSpecified;
        
        private uint minHeightField;
        
        private bool minHeightFieldSpecified;
        
        private uint maxHeightField;
        
        private bool maxHeightFieldSpecified;
        
        private string minFrameRateField;
        
        private string maxFrameRateField;
        
        private string segmentAlignmentField;
        
        private string subsegmentAlignmentField;
        
        private uint subsegmentStartsWithSAPField;
        
        private bool bitstreamSwitchingField;
        
        private bool bitstreamSwitchingFieldSpecified;
        
        public AdaptationSetType() {
            this.actuateField = actuateType.onRequest;
            //this.segmentAlignmentField = "false";
            //this.subsegmentAlignmentField = "false";
            this.subsegmentStartsWithSAPField = ((uint)(0));
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Accessibility")]
        public DescriptorType[] Accessibility {
            get {
                return this.accessibilityField;
            }
            set {
                this.accessibilityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Role")]
        public DescriptorType[] Role {
            get {
                return this.roleField;
            }
            set {
                this.roleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Rating")]
        public DescriptorType[] Rating {
            get {
                return this.ratingField;
            }
            set {
                this.ratingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Viewpoint")]
        public DescriptorType[] Viewpoint {
            get {
                return this.viewpointField;
            }
            set {
                this.viewpointField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ContentComponent")]
        public ContentComponentType[] ContentComponent {
            get {
                return this.contentComponentField;
            }
            set {
                this.contentComponentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BaseURL")]
        public BaseURLType[] BaseURL {
            get {
                return this.baseURLField;
            }
            set {
                this.baseURLField = value;
            }
        }
        
        /// <remarks/>
        public SegmentBaseType SegmentBase {
            get {
                return this.segmentBaseField;
            }
            set {
                this.segmentBaseField = value;
            }
        }
        
        /// <remarks/>
        public SegmentListType SegmentList {
            get {
                return this.segmentListField;
            }
            set {
                this.segmentListField = value;
            }
        }
        
        /// <remarks/>
        public SegmentTemplateType SegmentTemplate {
            get {
                return this.segmentTemplateField;
            }
            set {
                this.segmentTemplateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Representation")]
        public RepresentationType[] Representation {
            get {
                return this.representationField;
            }
            set {
                this.representationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/1999/xlink", DataType="anyURI")]
        public string href {
            get {
                return this.hrefField;
            }
            set {
                this.hrefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/1999/xlink")]
        [System.ComponentModel.DefaultValueAttribute(actuateType.onRequest)]
        public actuateType actuate {
            get {
                return this.actuateField;
            }
            set {
                this.actuateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint group {
            get {
                return this.groupField;
            }
            set {
                this.groupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool groupSpecified {
            get {
                return this.groupFieldSpecified;
            }
            set {
                this.groupFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="language")]
        public string lang {
            get {
                return this.langField;
            }
            set {
                this.langField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string contentType {
            get {
                return this.contentTypeField;
            }
            set {
                this.contentTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string par {
            get {
                return this.parField;
            }
            set {
                this.parField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint minBandwidth {
            get {
                return this.minBandwidthField;
            }
            set {
                this.minBandwidthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool minBandwidthSpecified {
            get {
                return this.minBandwidthFieldSpecified;
            }
            set {
                this.minBandwidthFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint maxBandwidth {
            get {
                return this.maxBandwidthField;
            }
            set {
                this.maxBandwidthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxBandwidthSpecified {
            get {
                return this.maxBandwidthFieldSpecified;
            }
            set {
                this.maxBandwidthFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint minWidth {
            get {
                return this.minWidthField;
            }
            set {
                this.minWidthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool minWidthSpecified {
            get {
                return this.minWidthFieldSpecified;
            }
            set {
                this.minWidthFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint maxWidth {
            get {
                return this.maxWidthField;
            }
            set {
                this.maxWidthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxWidthSpecified {
            get {
                return this.maxWidthFieldSpecified;
            }
            set {
                this.maxWidthFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint minHeight {
            get {
                return this.minHeightField;
            }
            set {
                this.minHeightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool minHeightSpecified {
            get {
                return this.minHeightFieldSpecified;
            }
            set {
                this.minHeightFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint maxHeight {
            get {
                return this.maxHeightField;
            }
            set {
                this.maxHeightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxHeightSpecified {
            get {
                return this.maxHeightFieldSpecified;
            }
            set {
                this.maxHeightFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string minFrameRate {
            get {
                return this.minFrameRateField;
            }
            set {
                this.minFrameRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string maxFrameRate {
            get {
                return this.maxFrameRateField;
            }
            set {
                this.maxFrameRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("false")]
        public string segmentAlignment {
            get {
                return this.segmentAlignmentField;
            }
            set {
                this.segmentAlignmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("false")]
        public string subsegmentAlignment {
            get {
                return this.subsegmentAlignmentField;
            }
            set {
                this.subsegmentAlignmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(uint), "0")]
        public uint subsegmentStartsWithSAP {
            get {
                return this.subsegmentStartsWithSAPField;
            }
            set {
                this.subsegmentStartsWithSAPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool bitstreamSwitching {
            get {
                return this.bitstreamSwitchingField;
            }
            set {
                this.bitstreamSwitchingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool bitstreamSwitchingSpecified {
            get {
                return this.bitstreamSwitchingFieldSpecified;
            }
            set {
                this.bitstreamSwitchingFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mpeg:dash:schema:mpd:2011")]
    public partial class PeriodType {
        
        private BaseURLType[] baseURLField;
        
        private SegmentBaseType segmentBaseField;
        
        private SegmentListType segmentListField;
        
        private SegmentTemplateType segmentTemplateField;
        
        private DescriptorType assetIdentifierField;
        
        private EventStreamType[] eventStreamField;
        
        private AdaptationSetType[] adaptationSetField;
        
        private SubsetType[] subsetField;
        
        private DescriptorType[] supplementalPropertyField;
        
        private System.Xml.XmlElement[] anyField;
        
        private string hrefField;
        
        private actuateType actuateField;
        
        private string idField;
        
        private string startField;
        
        private string durationField;
        
        private bool bitstreamSwitchingField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        public PeriodType() {
            this.actuateField = actuateType.onRequest;
            this.bitstreamSwitchingField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BaseURL")]
        public BaseURLType[] BaseURL {
            get {
                return this.baseURLField;
            }
            set {
                this.baseURLField = value;
            }
        }
        
        /// <remarks/>
        public SegmentBaseType SegmentBase {
            get {
                return this.segmentBaseField;
            }
            set {
                this.segmentBaseField = value;
            }
        }
        
        /// <remarks/>
        public SegmentListType SegmentList {
            get {
                return this.segmentListField;
            }
            set {
                this.segmentListField = value;
            }
        }
        
        /// <remarks/>
        public SegmentTemplateType SegmentTemplate {
            get {
                return this.segmentTemplateField;
            }
            set {
                this.segmentTemplateField = value;
            }
        }
        
        /// <remarks/>
        public DescriptorType AssetIdentifier {
            get {
                return this.assetIdentifierField;
            }
            set {
                this.assetIdentifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EventStream")]
        public EventStreamType[] EventStream {
            get {
                return this.eventStreamField;
            }
            set {
                this.eventStreamField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AdaptationSet")]
        public AdaptationSetType[] AdaptationSet {
            get {
                return this.adaptationSetField;
            }
            set {
                this.adaptationSetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Subset")]
        public SubsetType[] Subset {
            get {
                return this.subsetField;
            }
            set {
                this.subsetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SupplementalProperty")]
        public DescriptorType[] SupplementalProperty {
            get {
                return this.supplementalPropertyField;
            }
            set {
                this.supplementalPropertyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/1999/xlink", DataType="anyURI")]
        public string href {
            get {
                return this.hrefField;
            }
            set {
                this.hrefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/1999/xlink")]
        [System.ComponentModel.DefaultValueAttribute(actuateType.onRequest)]
        public actuateType actuate {
            get {
                return this.actuateField;
            }
            set {
                this.actuateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="duration")]
        public string start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="duration")]
        public string duration {
            get {
                return this.durationField;
            }
            set {
                this.durationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool bitstreamSwitching {
            get {
                return this.bitstreamSwitchingField;
            }
            set {
                this.bitstreamSwitchingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:mpeg:dash:schema:mpd:2011")]
    public enum PresentationType {
        
        /// <remarks/>
        @static,
        
        /// <remarks/>
        dynamic,
    }
}
