/*!
 * https://github.com/SamsungDForum/JuvoPlayer
 * Copyright 2018, Samsung Electronics Co., Ltd
 * Licensed under the MIT license
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

// <auto-generated/>

namespace JuvoPlayer.Demuxers.FFmpeg.Interop
{
    internal struct AVAudioFifo
    {
    }

    internal struct AVBPrint
    {
    }

    internal struct AVBuffer
    {
    }

    internal struct AVBufferPool
    {
    }

    internal struct AVDictionary
    {
    }

    internal struct SwrContext
    {
    }

    internal struct SwsContext
    {
    }

    internal struct AVCodecDefault
    {
    }

    internal struct AVCodecInternal
    {
    }

    internal struct MpegEncContext
    {
    }

    internal struct ReSampleContext
    {
    }

    internal struct AVBSFInternal
    {
    }

    internal struct AVBSFList
    {
    }

    internal struct AVResampleContext
    {
    }

    internal struct AVStreamInternal
    {
    }

    internal struct FFFrac
    {
    }

    internal struct AVFormatInternal
    {
    }

    internal struct AVCodecTag
    {
    }

    internal struct URLContext
    {
    }

    internal struct AVFilterPad
    {
    }

    internal struct AVFilterFormats
    {
    }

    internal struct AVFilterChannelLayouts
    {
    }

    internal struct AVFilterGraphInternal
    {
    }

    internal struct AVFilterInternal
    {
    }

    internal struct AVFilterCommand
    {
    }
}
