/*!
 * https://github.com/SamsungDForum/JuvoPlayer
 * Copyright 2018, Samsung Electronics Co., Ltd
 * Licensed under the MIT license
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

// <auto-generated/>

using System;
using System.Runtime.InteropServices;

namespace JuvoPlayer.Demuxers.FFmpeg.Interop
{
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate string AVClass_item_name(void* ctx);

    internal struct AVClass_item_name_func
    {
        public IntPtr Pointer;

        public static implicit operator AVClass_item_name_func(AVClass_item_name func)
        {
            return new AVClass_item_name_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate void* AVClass_child_next(void* obj, void* prev);

    internal struct AVClass_child_next_func
    {
        public IntPtr Pointer;

        public static implicit operator AVClass_child_next_func(AVClass_child_next func)
        {
            return new AVClass_child_next_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate AVClass* AVClass_child_class_next(AVClass* prev);

    internal struct AVClass_child_class_next_func
    {
        public IntPtr Pointer;

        public static implicit operator AVClass_child_class_next_func(AVClass_child_class_next func)
        {
            return new AVClass_child_class_next_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate AVClassCategory AVClass_get_category(void* ctx);

    internal struct AVClass_get_category_func
    {
        public IntPtr Pointer;

        public static implicit operator AVClass_get_category_func(AVClass_get_category func)
        {
            return new AVClass_get_category_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate int AVClass_query_ranges(AVOptionRanges** p0, void* obj,
        [MarshalAs(UnmanagedType.LPStr)] string key, int flags);

    internal struct AVClass_query_ranges_func
    {
        public IntPtr Pointer;

        public static implicit operator AVClass_query_ranges_func(AVClass_query_ranges func)
        {
            return new AVClass_query_ranges_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate void av_fifo_generic_peek_at_func(void* p0, void* p1, int p2);

    internal struct av_fifo_generic_peek_at_func_func
    {
        public IntPtr Pointer;

        public static implicit operator av_fifo_generic_peek_at_func_func(av_fifo_generic_peek_at_func func)
        {
            return new av_fifo_generic_peek_at_func_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate void av_fifo_generic_peek_func(void* p0, void* p1, int p2);

    internal struct av_fifo_generic_peek_func_func
    {
        public IntPtr Pointer;

        public static implicit operator av_fifo_generic_peek_func_func(av_fifo_generic_peek_func func)
        {
            return new av_fifo_generic_peek_func_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate void av_fifo_generic_read_func(void* p0, void* p1, int p2);

    internal struct av_fifo_generic_read_func_func
    {
        public IntPtr Pointer;

        public static implicit operator av_fifo_generic_read_func_func(av_fifo_generic_read_func func)
        {
            return new av_fifo_generic_read_func_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate int av_fifo_generic_write_func(void* p0, void* p1, int p2);

    internal struct av_fifo_generic_write_func_func
    {
        public IntPtr Pointer;

        public static implicit operator av_fifo_generic_write_func_func(av_fifo_generic_write_func func)
        {
            return new av_fifo_generic_write_func_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate int AVCodec_init_thread_copy(AVCodecContext* p0);

    internal struct AVCodec_init_thread_copy_func
    {
        public IntPtr Pointer;

        public static implicit operator AVCodec_init_thread_copy_func(AVCodec_init_thread_copy func)
        {
            return new AVCodec_init_thread_copy_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate int AVCodec_update_thread_context(AVCodecContext* dst, AVCodecContext* src);

    internal struct AVCodec_update_thread_context_func
    {
        public IntPtr Pointer;

        public static implicit operator AVCodec_update_thread_context_func(AVCodec_update_thread_context func)
        {
            return new AVCodec_update_thread_context_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate void AVCodec_init_static_data(AVCodec* codec);

    internal struct AVCodec_init_static_data_func
    {
        public IntPtr Pointer;

        public static implicit operator AVCodec_init_static_data_func(AVCodec_init_static_data func)
        {
            return new AVCodec_init_static_data_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate int AVCodec_init(AVCodecContext* p0);

    internal struct AVCodec_init_func
    {
        public IntPtr Pointer;

        public static implicit operator AVCodec_init_func(AVCodec_init func)
        {
            return new AVCodec_init_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate int AVCodec_encode_sub(AVCodecContext* p0, byte* buf, int buf_size, AVSubtitle* sub);

    internal struct AVCodec_encode_sub_func
    {
        public IntPtr Pointer;

        public static implicit operator AVCodec_encode_sub_func(AVCodec_encode_sub func)
        {
            return new AVCodec_encode_sub_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate int AVCodec_encode2(AVCodecContext* avctx, AVPacket* avpkt, AVFrame* frame,
        int* got_packet_ptr);

    internal struct AVCodec_encode2_func
    {
        public IntPtr Pointer;

        public static implicit operator AVCodec_encode2_func(AVCodec_encode2 func)
        {
            return new AVCodec_encode2_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate int AVCodec_decode(AVCodecContext* p0, void* outdata, int* outdata_size, AVPacket* avpkt);

    internal struct AVCodec_decode_func
    {
        public IntPtr Pointer;

        public static implicit operator AVCodec_decode_func(AVCodec_decode func)
        {
            return new AVCodec_decode_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate int AVCodec_close(AVCodecContext* p0);

    internal struct AVCodec_close_func
    {
        public IntPtr Pointer;

        public static implicit operator AVCodec_close_func(AVCodec_close func)
        {
            return new AVCodec_close_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate int AVCodec_send_frame(AVCodecContext* avctx, AVFrame* frame);

    internal struct AVCodec_send_frame_func
    {
        public IntPtr Pointer;

        public static implicit operator AVCodec_send_frame_func(AVCodec_send_frame func)
        {
            return new AVCodec_send_frame_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate int AVCodec_send_packet(AVCodecContext* avctx, AVPacket* avpkt);

    internal struct AVCodec_send_packet_func
    {
        public IntPtr Pointer;

        public static implicit operator AVCodec_send_packet_func(AVCodec_send_packet func)
        {
            return new AVCodec_send_packet_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate int AVCodec_receive_frame(AVCodecContext* avctx, AVFrame* frame);

    internal struct AVCodec_receive_frame_func
    {
        public IntPtr Pointer;

        public static implicit operator AVCodec_receive_frame_func(AVCodec_receive_frame func)
        {
            return new AVCodec_receive_frame_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate int AVCodec_receive_packet(AVCodecContext* avctx, AVPacket* avpkt);

    internal struct AVCodec_receive_packet_func
    {
        public IntPtr Pointer;

        public static implicit operator AVCodec_receive_packet_func(AVCodec_receive_packet func)
        {
            return new AVCodec_receive_packet_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate void AVCodec_flush(AVCodecContext* p0);

    internal struct AVCodec_flush_func
    {
        public IntPtr Pointer;

        public static implicit operator AVCodec_flush_func(AVCodec_flush func)
        {
            return new AVCodec_flush_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate void AVCodecContext_draw_horiz_band(AVCodecContext* s, AVFrame* src, ref int_array8 offset,
        int y, int type, int height);

    internal struct AVCodecContext_draw_horiz_band_func
    {
        public IntPtr Pointer;

        public static implicit operator AVCodecContext_draw_horiz_band_func(AVCodecContext_draw_horiz_band func)
        {
            return new AVCodecContext_draw_horiz_band_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate AVPixelFormat AVCodecContext_get_format(AVCodecContext* s, AVPixelFormat* fmt);

    internal struct AVCodecContext_get_format_func
    {
        public IntPtr Pointer;

        public static implicit operator AVCodecContext_get_format_func(AVCodecContext_get_format func)
        {
            return new AVCodecContext_get_format_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate int AVCodecContext_get_buffer2(AVCodecContext* s, AVFrame* frame, int flags);

    internal struct AVCodecContext_get_buffer2_func
    {
        public IntPtr Pointer;

        public static implicit operator AVCodecContext_get_buffer2_func(AVCodecContext_get_buffer2 func)
        {
            return new AVCodecContext_get_buffer2_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate void AVCodecContext_rtp_callback(AVCodecContext* avctx, void* data, int size, int mb_nb);

    internal struct AVCodecContext_rtp_callback_func
    {
        public IntPtr Pointer;

        public static implicit operator AVCodecContext_rtp_callback_func(AVCodecContext_rtp_callback func)
        {
            return new AVCodecContext_rtp_callback_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate int AVHWAccel_alloc_frame(AVCodecContext* avctx, AVFrame* frame);

    internal struct AVHWAccel_alloc_frame_func
    {
        public IntPtr Pointer;

        public static implicit operator AVHWAccel_alloc_frame_func(AVHWAccel_alloc_frame func)
        {
            return new AVHWAccel_alloc_frame_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate int AVHWAccel_start_frame(AVCodecContext* avctx, byte* buf, uint buf_size);

    internal struct AVHWAccel_start_frame_func
    {
        public IntPtr Pointer;

        public static implicit operator AVHWAccel_start_frame_func(AVHWAccel_start_frame func)
        {
            return new AVHWAccel_start_frame_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate int AVHWAccel_decode_slice(AVCodecContext* avctx, byte* buf, uint buf_size);

    internal struct AVHWAccel_decode_slice_func
    {
        public IntPtr Pointer;

        public static implicit operator AVHWAccel_decode_slice_func(AVHWAccel_decode_slice func)
        {
            return new AVHWAccel_decode_slice_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate int AVHWAccel_end_frame(AVCodecContext* avctx);

    internal struct AVHWAccel_end_frame_func
    {
        public IntPtr Pointer;

        public static implicit operator AVHWAccel_end_frame_func(AVHWAccel_end_frame func)
        {
            return new AVHWAccel_end_frame_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate void AVHWAccel_decode_mb(MpegEncContext* s);

    internal struct AVHWAccel_decode_mb_func
    {
        public IntPtr Pointer;

        public static implicit operator AVHWAccel_decode_mb_func(AVHWAccel_decode_mb func)
        {
            return new AVHWAccel_decode_mb_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate int AVHWAccel_init(AVCodecContext* avctx);

    internal struct AVHWAccel_init_func
    {
        public IntPtr Pointer;

        public static implicit operator AVHWAccel_init_func(AVHWAccel_init func)
        {
            return new AVHWAccel_init_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate int AVHWAccel_uninit(AVCodecContext* avctx);

    internal struct AVHWAccel_uninit_func
    {
        public IntPtr Pointer;

        public static implicit operator AVHWAccel_uninit_func(AVHWAccel_uninit func)
        {
            return new AVHWAccel_uninit_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate int AVCodecContext_execute(AVCodecContext* c, func_func func, void* arg2, int* ret,
        int count, int size);

    internal struct AVCodecContext_execute_func
    {
        public IntPtr Pointer;

        public static implicit operator AVCodecContext_execute_func(AVCodecContext_execute func)
        {
            return new AVCodecContext_execute_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate int AVCodecContext_execute2(AVCodecContext* c, func_func func, void* arg2, int* ret,
        int count);

    internal struct AVCodecContext_execute2_func
    {
        public IntPtr Pointer;

        public static implicit operator AVCodecContext_execute2_func(AVCodecContext_execute2 func)
        {
            return new AVCodecContext_execute2_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate int AVCodecParser_parser_init(AVCodecParserContext* s);

    internal struct AVCodecParser_parser_init_func
    {
        public IntPtr Pointer;

        public static implicit operator AVCodecParser_parser_init_func(AVCodecParser_parser_init func)
        {
            return new AVCodecParser_parser_init_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate int AVCodecParser_parser_parse(AVCodecParserContext* s, AVCodecContext* avctx,
        byte** poutbuf, int* poutbuf_size, byte* buf, int buf_size);

    internal struct AVCodecParser_parser_parse_func
    {
        public IntPtr Pointer;

        public static implicit operator AVCodecParser_parser_parse_func(AVCodecParser_parser_parse func)
        {
            return new AVCodecParser_parser_parse_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate void AVCodecParser_parser_close(AVCodecParserContext* s);

    internal struct AVCodecParser_parser_close_func
    {
        public IntPtr Pointer;

        public static implicit operator AVCodecParser_parser_close_func(AVCodecParser_parser_close func)
        {
            return new AVCodecParser_parser_close_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate int AVCodecParser_split(AVCodecContext* avctx, byte* buf, int buf_size);

    internal struct AVCodecParser_split_func
    {
        public IntPtr Pointer;

        public static implicit operator AVCodecParser_split_func(AVCodecParser_split func)
        {
            return new AVCodecParser_split_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate int AVBitStreamFilter_init(AVBSFContext* ctx);

    internal struct AVBitStreamFilter_init_func
    {
        public IntPtr Pointer;

        public static implicit operator AVBitStreamFilter_init_func(AVBitStreamFilter_init func)
        {
            return new AVBitStreamFilter_init_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate int AVBitStreamFilter_filter(AVBSFContext* ctx, AVPacket* pkt);

    internal struct AVBitStreamFilter_filter_func
    {
        public IntPtr Pointer;

        public static implicit operator AVBitStreamFilter_filter_func(AVBitStreamFilter_filter func)
        {
            return new AVBitStreamFilter_filter_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate void AVBitStreamFilter_close(AVBSFContext* ctx);

    internal struct AVBitStreamFilter_close_func
    {
        public IntPtr Pointer;

        public static implicit operator AVBitStreamFilter_close_func(AVBitStreamFilter_close func)
        {
            return new AVBitStreamFilter_close_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate int AVInputFormat_read_probe(AVProbeData* p0);

    internal struct AVInputFormat_read_probe_func
    {
        public IntPtr Pointer;

        public static implicit operator AVInputFormat_read_probe_func(AVInputFormat_read_probe func)
        {
            return new AVInputFormat_read_probe_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate int AVInputFormat_read_header(AVFormatContext* p0);

    internal struct AVInputFormat_read_header_func
    {
        public IntPtr Pointer;

        public static implicit operator AVInputFormat_read_header_func(AVInputFormat_read_header func)
        {
            return new AVInputFormat_read_header_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate int AVInputFormat_read_packet(AVFormatContext* p0, AVPacket* pkt);

    internal struct AVInputFormat_read_packet_func
    {
        public IntPtr Pointer;

        public static implicit operator AVInputFormat_read_packet_func(AVInputFormat_read_packet func)
        {
            return new AVInputFormat_read_packet_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate int AVInputFormat_read_close(AVFormatContext* p0);

    internal struct AVInputFormat_read_close_func
    {
        public IntPtr Pointer;

        public static implicit operator AVInputFormat_read_close_func(AVInputFormat_read_close func)
        {
            return new AVInputFormat_read_close_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate int AVInputFormat_read_seek(AVFormatContext* p0, int stream_index, long timestamp,
        int flags);

    internal struct AVInputFormat_read_seek_func
    {
        public IntPtr Pointer;

        public static implicit operator AVInputFormat_read_seek_func(AVInputFormat_read_seek func)
        {
            return new AVInputFormat_read_seek_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate long AVInputFormat_read_timestamp(AVFormatContext* s, int stream_index, long* pos,
        long pos_limit);

    internal struct AVInputFormat_read_timestamp_func
    {
        public IntPtr Pointer;

        public static implicit operator AVInputFormat_read_timestamp_func(AVInputFormat_read_timestamp func)
        {
            return new AVInputFormat_read_timestamp_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate int AVInputFormat_read_play(AVFormatContext* p0);

    internal struct AVInputFormat_read_play_func
    {
        public IntPtr Pointer;

        public static implicit operator AVInputFormat_read_play_func(AVInputFormat_read_play func)
        {
            return new AVInputFormat_read_play_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate int AVInputFormat_read_pause(AVFormatContext* p0);

    internal struct AVInputFormat_read_pause_func
    {
        public IntPtr Pointer;

        public static implicit operator AVInputFormat_read_pause_func(AVInputFormat_read_pause func)
        {
            return new AVInputFormat_read_pause_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate int AVInputFormat_read_seek2(AVFormatContext* s, int stream_index, long min_ts, long ts,
        long max_ts, int flags);

    internal struct AVInputFormat_read_seek2_func
    {
        public IntPtr Pointer;

        public static implicit operator AVInputFormat_read_seek2_func(AVInputFormat_read_seek2 func)
        {
            return new AVInputFormat_read_seek2_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate int AVInputFormat_get_device_list(AVFormatContext* s, AVDeviceInfoList* device_list);

    internal struct AVInputFormat_get_device_list_func
    {
        public IntPtr Pointer;

        public static implicit operator AVInputFormat_get_device_list_func(AVInputFormat_get_device_list func)
        {
            return new AVInputFormat_get_device_list_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate int AVInputFormat_create_device_capabilities(AVFormatContext* s,
        AVDeviceCapabilitiesQuery* caps);

    internal struct AVInputFormat_create_device_capabilities_func
    {
        public IntPtr Pointer;

        public static implicit operator AVInputFormat_create_device_capabilities_func(
            AVInputFormat_create_device_capabilities func)
        {
            return new AVInputFormat_create_device_capabilities_func
            {
                Pointer = Marshal.GetFunctionPointerForDelegate(func)
            };
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate int AVInputFormat_free_device_capabilities(AVFormatContext* s,
        AVDeviceCapabilitiesQuery* caps);

    internal struct AVInputFormat_free_device_capabilities_func
    {
        public IntPtr Pointer;

        public static implicit operator AVInputFormat_free_device_capabilities_func(
            AVInputFormat_free_device_capabilities func)
        {
            return new AVInputFormat_free_device_capabilities_func
            {
                Pointer = Marshal.GetFunctionPointerForDelegate(func)
            };
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate int AVIOContext_read_packet(void* opaque, byte* buf, int buf_size);

    internal struct AVIOContext_read_packet_func
    {
        public IntPtr Pointer;

        public static implicit operator AVIOContext_read_packet_func(AVIOContext_read_packet func)
        {
            return new AVIOContext_read_packet_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate int AVIOContext_write_packet(void* opaque, byte* buf, int buf_size);

    internal struct AVIOContext_write_packet_func
    {
        public IntPtr Pointer;

        public static implicit operator AVIOContext_write_packet_func(AVIOContext_write_packet func)
        {
            return new AVIOContext_write_packet_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate long AVIOContext_seek(void* opaque, long offset, int whence);

    internal struct AVIOContext_seek_func
    {
        public IntPtr Pointer;

        public static implicit operator AVIOContext_seek_func(AVIOContext_seek func)
        {
            return new AVIOContext_seek_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate ulong AVIOContext_update_checksum(ulong checksum, byte* buf, uint size);

    internal struct AVIOContext_update_checksum_func
    {
        public IntPtr Pointer;

        public static implicit operator AVIOContext_update_checksum_func(AVIOContext_update_checksum func)
        {
            return new AVIOContext_update_checksum_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate int AVIOContext_read_pause(void* opaque, int pause);

    internal struct AVIOContext_read_pause_func
    {
        public IntPtr Pointer;

        public static implicit operator AVIOContext_read_pause_func(AVIOContext_read_pause func)
        {
            return new AVIOContext_read_pause_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate long AVIOContext_read_seek(void* opaque, int stream_index, long timestamp, int flags);

    internal struct AVIOContext_read_seek_func
    {
        public IntPtr Pointer;

        public static implicit operator AVIOContext_read_seek_func(AVIOContext_read_seek func)
        {
            return new AVIOContext_read_seek_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate int AVIOContext_write_data_type(void* opaque, byte* buf, int buf_size,
        AVIODataMarkerType type, long time);

    internal struct AVIOContext_write_data_type_func
    {
        public IntPtr Pointer;

        public static implicit operator AVIOContext_write_data_type_func(AVIOContext_write_data_type func)
        {
            return new AVIOContext_write_data_type_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate int AVIOContext_short_seek_get(void* opaque);

    internal struct AVIOContext_short_seek_get_func
    {
        public IntPtr Pointer;

        public static implicit operator AVIOContext_short_seek_get_func(AVIOContext_short_seek_get func)
        {
            return new AVIOContext_short_seek_get_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate int AVIOInterruptCB_callback(void* p0);

    internal struct AVIOInterruptCB_callback_func
    {
        public IntPtr Pointer;

        public static implicit operator AVIOInterruptCB_callback_func(AVIOInterruptCB_callback func)
        {
            return new AVIOInterruptCB_callback_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate int AVFormatContext_control_message_cb(AVFormatContext* s, int type, void* data,
        ulong data_size);

    internal struct AVFormatContext_control_message_cb_func
    {
        public IntPtr Pointer;

        public static implicit operator AVFormatContext_control_message_cb_func(AVFormatContext_control_message_cb func)
        {
            return new AVFormatContext_control_message_cb_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate int AVFormatContext_open_cb(AVFormatContext* s, AVIOContext** p,
        [MarshalAs(UnmanagedType.LPStr)] string url, int flags, AVIOInterruptCB* int_cb, AVDictionary** options);

    internal struct AVFormatContext_open_cb_func
    {
        public IntPtr Pointer;

        public static implicit operator AVFormatContext_open_cb_func(AVFormatContext_open_cb func)
        {
            return new AVFormatContext_open_cb_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate int AVFormatContext_io_open(AVFormatContext* s, AVIOContext** pb,
        [MarshalAs(UnmanagedType.LPStr)] string url, int flags, AVDictionary** options);

    internal struct AVFormatContext_io_open_func
    {
        public IntPtr Pointer;

        public static implicit operator AVFormatContext_io_open_func(AVFormatContext_io_open func)
        {
            return new AVFormatContext_io_open_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate void AVFormatContext_io_close(AVFormatContext* s, AVIOContext* pb);

    internal struct AVFormatContext_io_close_func
    {
        public IntPtr Pointer;

        public static implicit operator AVFormatContext_io_close_func(AVFormatContext_io_close func)
        {
            return new AVFormatContext_io_close_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate int AVOutputFormat_write_header(AVFormatContext* p0);

    internal struct AVOutputFormat_write_header_func
    {
        public IntPtr Pointer;

        public static implicit operator AVOutputFormat_write_header_func(AVOutputFormat_write_header func)
        {
            return new AVOutputFormat_write_header_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate int AVOutputFormat_write_packet(AVFormatContext* p0, AVPacket* pkt);

    internal struct AVOutputFormat_write_packet_func
    {
        public IntPtr Pointer;

        public static implicit operator AVOutputFormat_write_packet_func(AVOutputFormat_write_packet func)
        {
            return new AVOutputFormat_write_packet_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate int AVOutputFormat_write_trailer(AVFormatContext* p0);

    internal struct AVOutputFormat_write_trailer_func
    {
        public IntPtr Pointer;

        public static implicit operator AVOutputFormat_write_trailer_func(AVOutputFormat_write_trailer func)
        {
            return new AVOutputFormat_write_trailer_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate int AVOutputFormat_interleave_packet(AVFormatContext* p0, AVPacket* @out, AVPacket* @in,
        int flush);

    internal struct AVOutputFormat_interleave_packet_func
    {
        public IntPtr Pointer;

        public static implicit operator AVOutputFormat_interleave_packet_func(AVOutputFormat_interleave_packet func)
        {
            return new AVOutputFormat_interleave_packet_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal delegate int AVOutputFormat_query_codec(AVCodecID id, int std_compliance);

    internal struct AVOutputFormat_query_codec_func
    {
        public IntPtr Pointer;

        public static implicit operator AVOutputFormat_query_codec_func(AVOutputFormat_query_codec func)
        {
            return new AVOutputFormat_query_codec_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate void AVOutputFormat_get_output_timestamp(AVFormatContext* s, int stream, long* dts,
        long* wall);

    internal struct AVOutputFormat_get_output_timestamp_func
    {
        public IntPtr Pointer;

        public static implicit operator AVOutputFormat_get_output_timestamp_func(
            AVOutputFormat_get_output_timestamp func)
        {
            return new AVOutputFormat_get_output_timestamp_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate int AVOutputFormat_control_message(AVFormatContext* s, int type, void* data,
        ulong data_size);

    internal struct AVOutputFormat_control_message_func
    {
        public IntPtr Pointer;

        public static implicit operator AVOutputFormat_control_message_func(AVOutputFormat_control_message func)
        {
            return new AVOutputFormat_control_message_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate int AVOutputFormat_write_uncoded_frame(AVFormatContext* p0, int stream_index,
        AVFrame** frame, uint flags);

    internal struct AVOutputFormat_write_uncoded_frame_func
    {
        public IntPtr Pointer;

        public static implicit operator AVOutputFormat_write_uncoded_frame_func(AVOutputFormat_write_uncoded_frame func)
        {
            return new AVOutputFormat_write_uncoded_frame_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate int AVOutputFormat_get_device_list(AVFormatContext* s, AVDeviceInfoList* device_list);

    internal struct AVOutputFormat_get_device_list_func
    {
        public IntPtr Pointer;

        public static implicit operator AVOutputFormat_get_device_list_func(AVOutputFormat_get_device_list func)
        {
            return new AVOutputFormat_get_device_list_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate int AVOutputFormat_create_device_capabilities(AVFormatContext* s,
        AVDeviceCapabilitiesQuery* caps);

    internal struct AVOutputFormat_create_device_capabilities_func
    {
        public IntPtr Pointer;

        public static implicit operator AVOutputFormat_create_device_capabilities_func(
            AVOutputFormat_create_device_capabilities func)
        {
            return new AVOutputFormat_create_device_capabilities_func
            {
                Pointer = Marshal.GetFunctionPointerForDelegate(func)
            };
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate int AVOutputFormat_free_device_capabilities(AVFormatContext* s,
        AVDeviceCapabilitiesQuery* caps);

    internal struct AVOutputFormat_free_device_capabilities_func
    {
        public IntPtr Pointer;

        public static implicit operator AVOutputFormat_free_device_capabilities_func(
            AVOutputFormat_free_device_capabilities func)
        {
            return new AVOutputFormat_free_device_capabilities_func
            {
                Pointer = Marshal.GetFunctionPointerForDelegate(func)
            };
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate int AVOutputFormat_init(AVFormatContext* p0);

    internal struct AVOutputFormat_init_func
    {
        public IntPtr Pointer;

        public static implicit operator AVOutputFormat_init_func(AVOutputFormat_init func)
        {
            return new AVOutputFormat_init_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate void AVOutputFormat_deinit(AVFormatContext* p0);

    internal struct AVOutputFormat_deinit_func
    {
        public IntPtr Pointer;

        public static implicit operator AVOutputFormat_deinit_func(AVOutputFormat_deinit func)
        {
            return new AVOutputFormat_deinit_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate int AVOutputFormat_check_bitstream(AVFormatContext* p0, AVPacket* pkt);

    internal struct AVOutputFormat_check_bitstream_func
    {
        public IntPtr Pointer;

        public static implicit operator AVOutputFormat_check_bitstream_func(AVOutputFormat_check_bitstream func)
        {
            return new AVOutputFormat_check_bitstream_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate int AVFilter_init(AVFilterContext* ctx);

    internal struct AVFilter_init_func
    {
        public IntPtr Pointer;

        public static implicit operator AVFilter_init_func(AVFilter_init func)
        {
            return new AVFilter_init_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate int AVFilter_init_dict(AVFilterContext* ctx, AVDictionary** options);

    internal struct AVFilter_init_dict_func
    {
        public IntPtr Pointer;

        public static implicit operator AVFilter_init_dict_func(AVFilter_init_dict func)
        {
            return new AVFilter_init_dict_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate void AVFilter_uninit(AVFilterContext* ctx);

    internal struct AVFilter_uninit_func
    {
        public IntPtr Pointer;

        public static implicit operator AVFilter_uninit_func(AVFilter_uninit func)
        {
            return new AVFilter_uninit_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate int AVFilter_query_formats(AVFilterContext* p0);

    internal struct AVFilter_query_formats_func
    {
        public IntPtr Pointer;

        public static implicit operator AVFilter_query_formats_func(AVFilter_query_formats func)
        {
            return new AVFilter_query_formats_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate int AVFilter_process_command(AVFilterContext* p0,
        [MarshalAs(UnmanagedType.LPStr)] string cmd, [MarshalAs(UnmanagedType.LPStr)] string arg, byte* res,
        int res_len, int flags);

    internal struct AVFilter_process_command_func
    {
        public IntPtr Pointer;

        public static implicit operator AVFilter_process_command_func(AVFilter_process_command func)
        {
            return new AVFilter_process_command_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate int AVFilter_init_opaque(AVFilterContext* ctx, void* opaque);

    internal struct AVFilter_init_opaque_func
    {
        public IntPtr Pointer;

        public static implicit operator AVFilter_init_opaque_func(AVFilter_init_opaque func)
        {
            return new AVFilter_init_opaque_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate int AVFilter_activate(AVFilterContext* ctx);

    internal struct AVFilter_activate_func
    {
        public IntPtr Pointer;

        public static implicit operator AVFilter_activate_func(AVFilter_activate func)
        {
            return new AVFilter_activate_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate int func(AVFilterContext* ctx, void* arg, int jobnr, int nb_jobs);

    internal struct func_func
    {
        public IntPtr Pointer;

        public static implicit operator func_func(func func)
        {
            return new func_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate int AVFilterGraph_execute(AVFilterContext* ctx, func_func func, void* arg, int* ret,
        int nb_jobs);

    internal struct AVFilterGraph_execute_func
    {
        public IntPtr Pointer;

        public static implicit operator AVFilterGraph_execute_func(AVFilterGraph_execute func)
        {
            return new AVFilterGraph_execute_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate void av_log_set_callback_callback(void* p0, int p1,
        [MarshalAs(UnmanagedType.LPStr)] string p2, byte* p3);

    internal struct av_log_set_callback_callback_func
    {
        public IntPtr Pointer;

        public static implicit operator av_log_set_callback_callback_func(av_log_set_callback_callback func)
        {
            return new av_log_set_callback_callback_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate void av_buffer_create_free(void* opaque, byte* data);

    internal struct av_buffer_create_free_func
    {
        public IntPtr Pointer;

        public static implicit operator av_buffer_create_free_func(av_buffer_create_free func)
        {
            return new av_buffer_create_free_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate AVBufferRef* av_buffer_pool_init_alloc(int size);

    internal struct av_buffer_pool_init_alloc_func
    {
        public IntPtr Pointer;

        public static implicit operator av_buffer_pool_init_alloc_func(av_buffer_pool_init_alloc func)
        {
            return new av_buffer_pool_init_alloc_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate AVBufferRef* av_buffer_pool_init2_alloc(void* opaque, int size);

    internal struct av_buffer_pool_init2_alloc_func
    {
        public IntPtr Pointer;

        public static implicit operator av_buffer_pool_init2_alloc_func(av_buffer_pool_init2_alloc func)
        {
            return new av_buffer_pool_init2_alloc_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate void av_buffer_pool_init2_pool_free(void* opaque);

    internal struct av_buffer_pool_init2_pool_free_func
    {
        public IntPtr Pointer;

        public static implicit operator av_buffer_pool_init2_pool_free_func(av_buffer_pool_init2_pool_free func)
        {
            return new av_buffer_pool_init2_pool_free_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate int avcodec_default_execute_func(AVCodecContext* c2, void* arg2);

    internal struct avcodec_default_execute_func_func
    {
        public IntPtr Pointer;

        public static implicit operator avcodec_default_execute_func_func(avcodec_default_execute_func func)
        {
            return new avcodec_default_execute_func_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate int avcodec_default_execute2_func(AVCodecContext* c2, void* arg2, int p2, int p3);

    internal struct avcodec_default_execute2_func_func
    {
        public IntPtr Pointer;

        public static implicit operator avcodec_default_execute2_func_func(avcodec_default_execute2_func func)
        {
            return new avcodec_default_execute2_func_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate int av_lockmgr_register_cb(void** mutex, AVLockOp op);

    internal struct av_lockmgr_register_cb_func
    {
        public IntPtr Pointer;

        public static implicit operator av_lockmgr_register_cb_func(av_lockmgr_register_cb func)
        {
            return new av_lockmgr_register_cb_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate int avio_alloc_context_read_packet(void* opaque, byte* buf, int buf_size);

    internal struct avio_alloc_context_read_packet_func
    {
        public IntPtr Pointer;

        public static implicit operator avio_alloc_context_read_packet_func(avio_alloc_context_read_packet func)
        {
            return new avio_alloc_context_read_packet_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate int avio_alloc_context_write_packet(void* opaque, byte* buf, int buf_size);

    internal struct avio_alloc_context_write_packet_func
    {
        public IntPtr Pointer;

        public static implicit operator avio_alloc_context_write_packet_func(avio_alloc_context_write_packet func)
        {
            return new avio_alloc_context_write_packet_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate long avio_alloc_context_seek(void* opaque, long offset, int whence);

    internal struct avio_alloc_context_seek_func
    {
        public IntPtr Pointer;

        public static implicit operator avio_alloc_context_seek_func(avio_alloc_context_seek func)
        {
            return new avio_alloc_context_seek_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate int av_format_get_control_message_cb(AVFormatContext* s, int type, void* data,
        ulong data_size);

    internal struct av_format_get_control_message_cb_func
    {
        public IntPtr Pointer;

        public static implicit operator av_format_get_control_message_cb_func(av_format_get_control_message_cb func)
        {
            return new av_format_get_control_message_cb_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate int av_format_set_control_message_cb_callback(AVFormatContext* s, int type, void* data,
        ulong data_size);

    internal struct av_format_set_control_message_cb_callback_func
    {
        public IntPtr Pointer;

        public static implicit operator av_format_set_control_message_cb_callback_func(
            av_format_set_control_message_cb_callback func)
        {
            return new av_format_set_control_message_cb_callback_func
            {
                Pointer = Marshal.GetFunctionPointerForDelegate(func)
            };
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate int av_format_get_open_cb(AVFormatContext* s, AVIOContext** pb,
        [MarshalAs(UnmanagedType.LPStr)] string url, int flags, AVIOInterruptCB* int_cb, AVDictionary** options);

    internal struct av_format_get_open_cb_func
    {
        public IntPtr Pointer;

        public static implicit operator av_format_get_open_cb_func(av_format_get_open_cb func)
        {
            return new av_format_get_open_cb_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    internal unsafe delegate int av_format_set_open_cb_callback(AVFormatContext* s, AVIOContext** pb,
        [MarshalAs(UnmanagedType.LPStr)] string url, int flags, AVIOInterruptCB* int_cb, AVDictionary** options);

    internal struct av_format_set_open_cb_callback_func
    {
        public IntPtr Pointer;

        public static implicit operator av_format_set_open_cb_callback_func(av_format_set_open_cb_callback func)
        {
            return new av_format_set_open_cb_callback_func {Pointer = Marshal.GetFunctionPointerForDelegate(func)};
        }
    }
}
